# SPDX-FileCopyrightText: 2026 Euro-Office contributors
# SPDX-License-Identifier: AGPL-3.0-only

version = 1

[[annotations]]
path = "OdfFile/Test/number_formats/currency.ods"
SPDX-FileCopyrightText = "2026 Euro-Office contributors"
SPDX-License-Identifier = "AGPL-3.0-only"
